version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bd_madre
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zuleta18
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nova_network

  backend:
    build: ./backend
    env_file:
      - ./backend/.env  # Cargar variables desde .env
    environment:
      # Entorno (development/production)
      - ENVIRONMENT=production
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - staticfiles:/app/staticfiles
      - ./backend/media:/app/media
    networks:
      - nova_network

  frontend:
    build: ./frontend
    networks:
      - nova_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - staticfiles:/app/static/
      - ./backend/media:/app/media/
      - /etc/letsencrypt/live/portafolio-juan.dagi.co/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/portafolio-juan.dagi.co/privkey.pem:/etc/ssl/private/privkey.pem
    networks:
      - nova_network

volumes:
  postgres_data:
  staticfiles:

networks:
  nova_network:
    driver: bridge
