# Generated by Django 5.0.6 on 2025-07-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='SKU'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['sku'], name='producto_sku_idx'),
        ),
    ]
