# Generated by Django 5.0.6 on 2025-07-30 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0002_producto_sku_producto_producto_sku_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imei',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='sucursal',
            field=models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='main_dashboard.sucursales'),
        ),
    ]
