# Generated by Django 5.0.6 on 2025-07-31 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0003_producto_imei_producto_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'descuentos',
            },
        ),
        migrations.CreateModel(
            name='TipoMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_medida',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='sucursal',
            field=models.ForeignKey(blank=True, db_column='sucursal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='main_dashboard.sucursales'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.ForeignKey(blank=True, db_column='descuento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_dashboard.descuento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_medida',
            field=models.ForeignKey(blank=True, db_column='tipo_medida_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_dashboard.tipomedida'),
        ),
    ]
