# Generated by Django 5.1.5 on 2025-08-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0004_descuento_tipomedida_alter_producto_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descuento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipomedida',
            options={'managed': False},
        ),
    ]
