# Generated by Django 5.1.5 on 2026-01-28 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0005_alter_descuento_options_alter_producto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('requiere_referencia', models.BooleanField(default=False)),
                ('permite_cambio', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'db_table': 'facturacion_forma_pago',
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('ALM', 'Almacén central'), ('SUC', 'Bodega de sucursal'), ('TRN', 'En tránsito'), ('CON', 'Consignación'), ('3PL', 'Operador logístico')], default='SUC', max_length=4)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('estatus', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodegas_responsables', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bodegas', to='main_dashboard.sucursales')),
            ],
            options={
                'db_table': 'inventario_bodega',
                'ordering': ('sucursal', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('NAT', 'Natural'), ('JUR', 'Jurídica')], default='NAT', max_length=3)),
                ('primer_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('n_registro_mercantil', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte')], max_length=3, null=True)),
                ('numero_documento', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_credito', models.IntegerField(default=0)),
                ('estatus', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'facturacion_cliente',
                'indexes': [models.Index(fields=['numero_documento'], name='facturacion_numero__63491b_idx'), models.Index(fields=['tipo_documento', 'numero_documento'], name='facturacion_tipo_do_d6b35c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo_factura', models.CharField(default='FACT', max_length=10)),
                ('consecutivo_actual', models.IntegerField(default=1)),
                ('longitud_consecutivo', models.IntegerField(default=6)),
                ('formato_impresion', models.CharField(choices=[('58mm', 'Térmico 58mm'), ('80mm', 'Térmico 80mm'), ('a4', 'Papel A4')], default='80mm', max_length=10)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('nit_empresa', models.CharField(max_length=50)),
                ('direccion_empresa', models.CharField(max_length=255)),
                ('telefono_empresa', models.CharField(max_length=20)),
                ('ciudad_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('pie_de_pagina', models.TextField(blank=True, null=True)),
                ('sucursal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='config_facturacion', to='main_dashboard.sucursales')),
            ],
            options={
                'verbose_name': 'Configuración de Facturación',
                'verbose_name_plural': 'Configuraciones de Facturación',
                'db_table': 'facturacion_config',
            },
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('reservado', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=0)),
                ('maximo', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='main_dashboard.bodega')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='main_dashboard.producto')),
            ],
            options={
                'db_table': 'inventario_existencia',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(db_index=True, max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('BOR', 'Borrador'), ('PAG', 'Pagada'), ('ANU', 'Anulada')], default='BOR', max_length=3)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cambio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_anuladas', to=settings.AUTH_USER_MODEL)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='main_dashboard.bodega')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='main_dashboard.cliente')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='main_dashboard.sucursales')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facturacion_factura',
                'ordering': ('-fecha_venta',),
            },
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=255)),
                ('producto_sku', models.CharField(max_length=50)),
                ('producto_imei', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('iva_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_devuelta', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='main_dashboard.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_factura', to='main_dashboard.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
                'db_table': 'facturacion_factura_detalle',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('autorizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='main_dashboard.factura')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_dashboard.formapago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'facturacion_pago',
            },
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BOR', 'Borrador'), ('ENV', 'Enviado'), ('REC', 'Recibido'), ('CAN', 'Cancelado')], default='BOR', max_length=3)),
                ('usar_bodega_transito', models.BooleanField(default=True, help_text='Si está activo, usa una bodega TRN durante el envío.')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('recibido_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_destino', to='main_dashboard.bodega')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_origen', to='main_dashboard.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventario_traslado',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='TrasladoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='lineas_traslado', to='main_dashboard.producto')),
                ('traslado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='main_dashboard.traslado')),
            ],
            options={
                'db_table': 'inventario_traslado_linea',
            },
        ),
        migrations.AddIndex(
            model_name='bodega',
            index=models.Index(fields=['sucursal', 'estatus'], name='inventario__sucursa_e85a55_idx'),
        ),
        migrations.AddIndex(
            model_name='bodega',
            index=models.Index(fields=['sucursal', 'tipo'], name='inventario__sucursa_fc8e25_idx'),
        ),
        migrations.AddConstraint(
            model_name='bodega',
            constraint=models.UniqueConstraint(fields=('sucursal', 'nombre'), name='uniq_bodega_nombre_por_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='bodega',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='uniq_bodega_codigo_por_sucursal'),
        ),
        migrations.AddIndex(
            model_name='existencia',
            index=models.Index(fields=['bodega'], name='inventario__bodega__2c8a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='existencia',
            index=models.Index(fields=['producto'], name='inventario__product_8958fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='existencia',
            constraint=models.UniqueConstraint(fields=('producto', 'bodega'), name='uniq_existencia_producto_bodega'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero_factura'], name='facturacion_numero__d0f299_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_venta'], name='facturacion_fecha_v_81230c_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado'], name='facturacion_estado_b4dd64_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente'], name='facturacion_cliente_1abe53_idx'),
        ),
        migrations.AddIndex(
            model_name='facturadetalle',
            index=models.Index(fields=['factura', 'producto'], name='facturacion_factura_f75558_idx'),
        ),
        migrations.AddIndex(
            model_name='trasladolinea',
            index=models.Index(fields=['traslado'], name='inventario__traslad_f6ca04_idx'),
        ),
        migrations.AddIndex(
            model_name='trasladolinea',
            index=models.Index(fields=['producto'], name='inventario__product_05ae78_idx'),
        ),
        migrations.AddConstraint(
            model_name='trasladolinea',
            constraint=models.UniqueConstraint(fields=('traslado', 'producto'), name='uniq_linea_por_producto_en_traslado'),
        ),
    ]
