# Generated by Django 5.1.5 on 2026-02-07 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0006_formapago_bodega_cliente_configuracionfactura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='anulada_por',
            field=models.ForeignKey(blank=True, db_column='anulada_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_anuladas', to=settings.AUTH_USER_MODEL),
        ),
    ]
