# Generated by Django 5.1.5 on 2026-02-17 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_dashboard', '0007_alter_factura_anulada_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PCT', 'Porcentaje'), ('VAL', 'Valor fijo')], default='PCT', max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Porcentaje (ej. 15.00) o valor monetario fijo según el tipo', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'db_table': 'cupones',
            },
        ),
        migrations.CreateModel(
            name='ClienteTienda',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente E-commerce'), ('admin', 'Administrador Tienda'), ('vendedor', 'Vendedor POS')], default='cliente', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente de Activación')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_tienda', to='main_dashboard.cliente')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='cliente_tienda_set', related_query_name='cliente_tienda', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='cliente_tienda_set', related_query_name='cliente_tienda', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Cliente Tienda',
                'verbose_name_plural': 'Clientes Tienda',
                'db_table': 'clientes_tienda',
                'indexes': [models.Index(fields=['email'], name='clientes_ti_email_bb7def_idx'), models.Index(fields=['estado'], name='clientes_ti_estado_e56e22_idx'), models.Index(fields=['cliente_id'], name='clientes_ti_cliente_467232_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClienteCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('cantidad_disponible', models.PositiveIntegerField(default=1)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupones_asignados', to='main_dashboard.cliente')),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_asignados', to='main_dashboard.cupon')),
            ],
            options={
                'verbose_name': 'Cupón de Cliente',
                'verbose_name_plural': 'Cupones de Clientes',
                'db_table': 'cliente_cupones',
                'unique_together': {('cliente', 'cupon')},
            },
        ),
    ]
