# Generated by Django 5.1.5 on 2026-03-15 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0011_remove_unique_numero_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_entradas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_salidas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_esperado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_contado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arqueos_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arqueo de Caja',
                'verbose_name_plural': 'Arqueos de Caja',
                'db_table': 'caja_arqueos',
                'ordering': ('-fecha', '-fecha_hora_registro'),
                'indexes': [models.Index(fields=['fecha', '-fecha_hora_registro'], name='caja_arqueo_fecha_96a707_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20)),
                ('categoria', models.CharField(max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='efectivo', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField(db_index=True)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='main_dashboard.factura')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'db_table': 'caja_movimientos',
                'ordering': ('-fecha_hora',),
                'indexes': [models.Index(fields=['fecha', '-fecha_hora'], name='caja_movimi_fecha_c2145e_idx'), models.Index(fields=['tipo', 'fecha'], name='caja_movimi_tipo_68aa76_idx'), models.Index(fields=['metodo_pago', 'fecha'], name='caja_movimi_metodo__0c788f_idx')],
            },
        ),
    ]
