# Generated by Django 5.1.5 on 2026-03-15 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0012_add_caja_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dias_mora',
            field=models.IntegerField(default=0, help_text='Días de mora calculados automáticamente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='en_mora',
            field=models.BooleanField(default=False, help_text='Indica si el cliente está en lista negra por mora'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_ultimo_pago',
            field=models.DateField(blank=True, help_text='Fecha del último pago realizado', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones_mora',
            field=models.TextField(blank=True, help_text='Observaciones sobre el estado de mora', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró al cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('nequi', 'Nequi'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='efectivo', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_abono', models.DateField(db_index=True)),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='main_dashboard.cliente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'db_table': 'facturacion_abono',
                'ordering': ['-fecha_abono', '-fecha_hora_registro'],
                'indexes': [models.Index(fields=['cliente', '-fecha_abono'], name='facturacion_cliente_1df6b1_idx'), models.Index(fields=['-fecha_abono'], name='facturacion_fecha_a_e929a4_idx')],
            },
        ),
    ]
