# Generated by Django 5.1.5 on 2026-03-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0013_cliente_dias_mora_cliente_en_mora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tipo_factura',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito/Fiado')], db_index=True, default='contado', help_text='Contado: paga al momento, Crédito: fiado que se paga después', max_length=10),
        ),
    ]
