# Generated by Django 5.1.5 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0014_factura_tipo_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='dia_pago',
            field=models.IntegerField(blank=True, help_text='Día del mes en que el cliente pagará (1-31). Solo para facturas de crédito.', null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cuotas',
            field=models.IntegerField(blank=True, help_text='Número de cuotas en las que se dividirá el pago. Solo para facturas de crédito.', null=True),
        ),
    ]
