# Generated by Django 5.1.5 on 2026-03-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0016_caja_sucursal_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='es_caja_menor',
            field=models.BooleanField(default=False),
        ),
    ]
