# Generated by Django 5.1.5 on 2026-03-19 05:34

import django.core.validators
import django.db.models.deletion
import main_dashboard.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0019_movimiento_caja_soporte_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('codigo_producto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código/SKU')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio al que el proveedor vende este producto', max_digits=12, verbose_name='Precio Unitario')),
                ('moneda', models.CharField(default='COP', max_length=10, verbose_name='Moneda')),
                ('tiempo_entrega_dias', models.IntegerField(blank=True, help_text='Días que tarda el proveedor en entregar este producto', null=True, verbose_name='Tiempo de Entrega (días)')),
                ('minimo_pedido', models.IntegerField(blank=True, help_text='Cantidad mínima que se debe pedir', null=True, verbose_name='Mínimo de Pedido')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('stock_actual', models.IntegerField(blank=True, help_text='Stock disponible según proveedor', null=True, verbose_name='Stock Actual')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto de Proveedor',
                'verbose_name_plural': 'Productos de Proveedores',
                'db_table': 'proveedor_productos',
                'ordering': ('nombre_producto',),
            },
        ),
        migrations.AlterField(
            model_name='abono',
            name='soporte_pago',
            field=models.FileField(blank=True, help_text='Soporte del pago (transferencia, nequi, tarjeta)', null=True, upload_to=main_dashboard.models.upload_soporte_abono),
        ),
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número de Pedido')),
                ('fecha_pedido', models.DateField(db_index=True, verbose_name='Fecha del Pedido')),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Estimada')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Real')),
                ('monto_subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('en_transito', 'En Tránsito'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas visibles solo para usuarios internos', null=True, verbose_name='Notas Internas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido a Proveedor',
                'verbose_name_plural': 'Pedidos a Proveedores',
                'db_table': 'proveedor_pedidos',
                'ordering': ('-fecha_pedido', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(verbose_name='Cantidad Solicitada')),
                ('cantidad_recibida', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Recibida')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='main_dashboard.pedidoproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedidos', to='main_dashboard.productoproveedor')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
                'db_table': 'proveedor_pedido_detalles',
                'ordering': ('pedido', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(db_index=True, help_text='Número de identificación tributaria del proveedor', max_length=50, unique=True, verbose_name='NIT/Identificación Fiscal')),
                ('razon_social', models.CharField(help_text='Nombre legal de la empresa proveedora', max_length=255, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, help_text='Nombre con el que se conoce comercialmente', max_length=255, null=True, verbose_name='Nombre Comercial')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección Física')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('pais', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('telefono_whatsapp', models.CharField(blank=True, help_text='Número de WhatsApp con código de país (ej: +573001234567)', max_length=20, null=True, verbose_name='WhatsApp')),
                ('contacto_principal', models.CharField(blank=True, help_text='Nombre de la persona principal de contacto', max_length=255, null=True, verbose_name='Persona de Contacto')),
                ('cargo_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Contacto')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('logo_url', models.URLField(blank=True, help_text='URL de la imagen del logo del proveedor', null=True, verbose_name='URL del Logo')),
                ('plazo_pago_dias', models.IntegerField(blank=True, help_text='Plazo en días para pagar facturas', null=True, verbose_name='Plazo de Pago (días)')),
                ('descuento_comercial', models.DecimalField(decimal_places=2, default=0, help_text='Descuento por volumen de compra', max_digits=5, verbose_name='Descuento Comercial (%)')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, help_text='Monto máximo de crédito otorgado', max_digits=12, verbose_name='Límite de Crédito')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado')], db_index=True, default='activo', max_length=20)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, help_text='Promedio de calificaciones (1-5)', max_digits=3, verbose_name='Calificación Promedio')),
                ('numero_calificaciones', models.IntegerField(default=0, verbose_name='Número de Calificaciones')),
                ('observaciones', models.TextField(blank=True, help_text='Notas generales sobre el proveedor', null=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ('razon_social',),
            },
        ),
        migrations.AddField(
            model_name='productoproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='main_dashboard.proveedor'),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='main_dashboard.proveedor'),
        ),
        migrations.CreateModel(
            name='DocumentoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('contrato', 'Contrato'), ('certificado', 'Certificado'), ('factura', 'Factura'), ('catalogo', 'Catálogo de Productos'), ('cotizacion', 'Cotización'), ('otro', 'Otro')], max_length=20)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='proveedores/documentos/%Y/%m/', verbose_name='Archivo')),
                ('url_externa', models.URLField(blank=True, help_text='Si el documento está en un sistema externo', null=True, verbose_name='URL Externa')),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Para contratos o certificados con vigencia', null=True, verbose_name='Fecha de Vencimiento')),
                ('generar_alerta_vencimiento', models.BooleanField(default=False, help_text='Enviar alerta antes de que venza', verbose_name='Generar Alerta de Vencimiento')),
                ('dias_alerta', models.IntegerField(blank=True, help_text='Días antes del vencimiento para enviar alerta', null=True, verbose_name='Días de Anticipación para Alerta')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='main_dashboard.proveedor')),
            ],
            options={
                'verbose_name': 'Documento de Proveedor',
                'verbose_name_plural': 'Documentos de Proveedores',
                'db_table': 'proveedor_documentos',
                'ordering': ('-fecha_emision', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='ContactoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contacto', models.CharField(choices=[('ventas', 'Ventas'), ('cobranza', 'Cobranza'), ('soporte', 'Soporte Técnico'), ('logistica', 'Logística/Distribución'), ('direccion', 'Dirección General'), ('otro', 'Otro')], default='ventas', max_length=20, verbose_name='Tipo de Contacto')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Contacto')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('telefono_whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('extension', models.CharField(blank=True, max_length=10, null=True, verbose_name='Extensión')),
                ('horario_contacto', models.CharField(blank=True, help_text='Ej: Lun-Vie 8am-5pm', max_length=100, null=True, verbose_name='Horario de Contacto')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('principal', models.BooleanField(default=False, help_text='Marcar como contacto principal para este tipo', verbose_name='Contacto Principal')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='main_dashboard.proveedor')),
            ],
            options={
                'verbose_name': 'Contacto de Proveedor',
                'verbose_name_plural': 'Contactos de Proveedores',
                'db_table': 'proveedor_contactos',
                'ordering': ('tipo_contacto', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='CalificacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_evaluacion', models.CharField(choices=[('calidad', 'Calidad de Productos'), ('tiempos_entrega', 'Tiempos de Entrega'), ('servicio', 'Servicio al Cliente'), ('precios', 'Precios Competitivos'), ('general', 'Evaluación General')], default='general', max_length=20)),
                ('calificacion', models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('puntos_fuertes', models.TextField(blank=True, help_text='Aspectos positivos del proveedor', null=True, verbose_name='Puntos Fuertes')),
                ('puntos_a_mejorar', models.TextField(blank=True, help_text='Aspectos que el proveedor debe mejorar', null=True, verbose_name='Puntos a Mejorar')),
                ('fecha_evaluacion', models.DateField(db_index=True, verbose_name='Fecha de Evaluación')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evaluado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_proveedores', to=settings.AUTH_USER_MODEL)),
                ('pedido_referencia', models.ForeignKey(blank=True, help_text='Pedido específico que se está evaluando', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='main_dashboard.pedidoproveedor')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='main_dashboard.proveedor')),
            ],
            options={
                'verbose_name': 'Calificación de Proveedor',
                'verbose_name_plural': 'Calificaciones de Proveedores',
                'db_table': 'proveedor_calificaciones',
                'ordering': ('-fecha_evaluacion', '-creado_en'),
            },
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['razon_social'], name='proveedores_razon_s_2d0255_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['nit'], name='proveedores_nit_dea009_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['estado'], name='proveedores_estado_e45323_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['calificacion_promedio'], name='proveedores_calific_1699e7_idx'),
        ),
        migrations.AddIndex(
            model_name='productoproveedor',
            index=models.Index(fields=['proveedor', 'nombre_producto'], name='proveedor_p_proveed_751c23_idx'),
        ),
        migrations.AddIndex(
            model_name='productoproveedor',
            index=models.Index(fields=['disponible'], name='proveedor_p_disponi_109c88_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoproveedor',
            index=models.Index(fields=['proveedor', '-fecha_pedido'], name='proveedor_p_proveed_e05a68_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoproveedor',
            index=models.Index(fields=['numero_pedido'], name='proveedor_p_numero__2c441e_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoproveedor',
            index=models.Index(fields=['estado'], name='proveedor_p_estado_e01c67_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoproveedor',
            index=models.Index(fields=['-fecha_pedido'], name='proveedor_p_fecha_p_f31114_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoproveedor',
            index=models.Index(fields=['proveedor', 'tipo_documento'], name='proveedor_d_proveed_ce6a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoproveedor',
            index=models.Index(fields=['fecha_vencimiento'], name='proveedor_d_fecha_v_cb2c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='contactoproveedor',
            index=models.Index(fields=['proveedor', 'tipo_contacto'], name='proveedor_c_proveed_fb4ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='contactoproveedor',
            index=models.Index(fields=['principal'], name='proveedor_c_princip_bae67e_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacionproveedor',
            index=models.Index(fields=['proveedor', '-fecha_evaluacion'], name='proveedor_c_proveed_d92ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacionproveedor',
            index=models.Index(fields=['categoria_evaluacion'], name='proveedor_c_categor_a93a15_idx'),
        ),
    ]
