# Generated by Django 5.1.5 on 2026-03-21 04:12

import main_dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0021_fix_proveedor_creado_por_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='soporte_pago',
            field=models.FileField(blank=True, help_text='Soporte del pago (transferencia, nequi, tarjeta)', null=True, upload_to=main_dashboard.models.upload_soporte_pago),
        ),
    ]
