# Generated by Django 5.1.5 on 2026-03-21 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0022_update_soporte_pago_path'),
    ]

    operations = [
    ]
