# Generated by Django 5.1.5 on 2026-03-21 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0023_update_abono_soporte_path'),
    ]

    operations = [
    ]
