# Generated by Django 5.1.5 on 2026-03-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0024_update_caja_menor_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, help_text='Ej: S, M, L, XL, 38, 40, etc.', max_length=50, null=True, verbose_name='Talla')),
                ('color', models.CharField(blank=True, help_text='Nombre del color', max_length=100, null=True, verbose_name='Color')),
                ('color_hex', models.CharField(blank=True, help_text='Ej: #FF5733 para colores personalizados', max_length=7, null=True, verbose_name='Código HEX')),
                ('medida', models.CharField(blank=True, help_text='Ej: 10x20cm, 500ml, 1kg, etc.', max_length=100, null=True, verbose_name='Medida')),
                ('sku_variante', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='SKU Variante')),
                ('stock', models.IntegerField(default=0, help_text='Stock específico de esta variante')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Precio diferencial de esta variante', max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_predeterminado', models.BooleanField(default=False, help_text='Marcar como variante por defecto')),
                ('imagen_variante', models.CharField(blank=True, help_text='URL de imagen específica de esta variante', max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='main_dashboard.producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'db_table': 'producto_variantes',
                'ordering': ('producto', 'color', 'talla', 'medida'),
                'indexes': [models.Index(fields=['producto', 'color'], name='producto_va_product_204f43_idx'), models.Index(fields=['producto', 'talla'], name='producto_va_product_04a566_idx'), models.Index(fields=['sku_variante'], name='producto_va_sku_var_996d79_idx'), models.Index(fields=['activo'], name='producto_va_activo_bf928b_idx')],
            },
        ),
    ]
