# Generated by Django 5.1.5 on 2026-03-25 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0025_producto_variante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productovariante',
            name='stock',
        ),
        migrations.CreateModel(
            name='KardexAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conteo', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha del Conteo')),
                ('total_productos', models.IntegerField(default=0)),
                ('productos_contados', models.IntegerField(default=0)),
                ('productos_cuadrados', models.IntegerField(default=0)),
                ('productos_con_diferencia', models.IntegerField(default=0)),
                ('porcentaje_precision', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_total_diferencias', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sugerencia', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validado', 'Validado'), ('aplicado', 'Aplicado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(db_column='sucursal_id', on_delete=django.db.models.deletion.CASCADE, to='main_dashboard.sucursales')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_registrados', to=settings.AUTH_USER_MODEL)),
                ('usuario_valido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste de Kardex',
                'verbose_name_plural': 'Ajustes de Kardex',
                'db_table': 'kardex_ajustes',
                'ordering': ('-fecha_conteo',),
            },
        ),
        migrations.CreateModel(
            name='KardexDiferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sistema', models.IntegerField(default=0)),
                ('cantidad_fisica', models.IntegerField(default=0)),
                ('diferencia', models.IntegerField(default=0)),
                ('tipo_diferencia', models.CharField(choices=[('faltante', 'Faltante'), ('sobrante', 'Sobrante'), ('cuadrado', 'Cuadrado')], default='cuadrado', max_length=20)),
                ('valor_diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('snapshot_nombre_producto', models.CharField(max_length=255)),
                ('snapshot_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('snapshot_precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('revisado', models.BooleanField(default=False)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('kardex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diferencias', to='main_dashboard.kardexajuste')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diferencias_kardex', to='main_dashboard.producto')),
            ],
            options={
                'verbose_name': 'Diferencia de Kardex',
                'verbose_name_plural': 'Diferencias de Kardex',
                'db_table': 'kardex_diferencias',
                'ordering': ['kardex', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='kardexajuste',
            index=models.Index(fields=['sucursal', '-fecha_conteo'], name='kardex_ajus_sucursa_cfd137_idx'),
        ),
        migrations.AddIndex(
            model_name='kardexajuste',
            index=models.Index(fields=['estado'], name='kardex_ajus_estado_a83b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='kardexajuste',
            index=models.Index(fields=['fecha_conteo'], name='kardex_ajus_fecha_c_2cc1aa_idx'),
        ),
        migrations.AddIndex(
            model_name='kardexdiferencia',
            index=models.Index(fields=['kardex', 'producto'], name='kardex_dife_kardex__101a18_idx'),
        ),
        migrations.AddIndex(
            model_name='kardexdiferencia',
            index=models.Index(fields=['tipo_diferencia'], name='kardex_dife_tipo_di_bf2400_idx'),
        ),
    ]
