# Generated by Django 5.1.5 on 2026-04-11 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0028_solicitud_apertura_caja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialLogin',
            fields=[
                ('id_historial', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario_id', models.IntegerField(db_column='usuario_id', help_text='ID del usuario en la tabla login_usuario (base de datos principal)')),
                ('usuario_correo', models.CharField(db_column='usuario_correo', help_text='Correo del usuario para referencia rápida', max_length=255)),
                ('usuario_nombre', models.CharField(db_column='usuario_nombre', help_text='Nombre de usuario para referencia rápida', max_length=100)),
                ('fecha_hora_login', models.DateTimeField(db_column='fecha_hora_login', db_index=True, help_text='Fecha y hora de inicio de sesión')),
                ('fecha_hora_logout', models.DateTimeField(blank=True, db_column='fecha_hora_logout', help_text='Fecha y hora de cierre de sesión', null=True)),
                ('direccion_ip', models.CharField(blank=True, db_column='direccion_ip', help_text='Dirección IP del usuario (IPv4 o IPv6)', max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, db_column='user_agent', help_text='User agent del navegador', null=True)),
                ('exitoso', models.BooleanField(db_column='exitoso', default=True, help_text='Indica si el login fue exitoso')),
                ('fallo_reason', models.CharField(blank=True, db_column='fallo_reason', help_text='Razón del fallo si no fue exitoso', max_length=255, null=True)),
                ('duracion_segundos', models.IntegerField(blank=True, db_column='duracion_segundos', help_text='Duración de la sesión en segundos', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
            ],
            options={
                'verbose_name': 'Historial de Login',
                'verbose_name_plural': 'Historiales de Login',
                'db_table': 'historial_login',
                'ordering': ['-fecha_hora_login'],
            },
        ),
        migrations.RemoveIndex(
            model_name='arqueocaja',
            name='main_dash_arqueo_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='arqueocaja',
            new_name='caja_arqueo_sucursa_18caf3_idx',
            old_name='main_dash_arqueo_suc_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitudaperturacaja',
            new_name='solicitudes_estado_8881a1_idx',
            old_name='main_dash_sol_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitudaperturacaja',
            new_name='solicitudes_sucursa_ced600_idx',
            old_name='main_dash_sol_suc_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitudaperturacaja',
            new_name='solicitudes_solicit_dd4709_idx',
            old_name='main_dash_sol_solic_idx',
        ),
        migrations.AlterField(
            model_name='solicitudaperturacaja',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='arqueocaja',
            index=models.Index(fields=['estado_caja'], name='caja_arqueo_estado__0a85f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='arqueocaja',
            constraint=models.CheckConstraint(condition=models.Q(('estado_caja__in', ['abierta', 'cerrada'])), name='check_estado_caja_valido'),
        ),
        migrations.AddIndex(
            model_name='historiallogin',
            index=models.Index(fields=['usuario_id'], name='historial_l_usuario_2c5cff_idx'),
        ),
        migrations.AddIndex(
            model_name='historiallogin',
            index=models.Index(fields=['fecha_hora_login'], name='historial_l_fecha_h_8fa8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='historiallogin',
            index=models.Index(fields=['direccion_ip'], name='historial_l_direcci_1745f7_idx'),
        ),
        migrations.AddIndex(
            model_name='historiallogin',
            index=models.Index(fields=['-fecha_hora_login', 'usuario_id'], name='historial_l_fecha_h_3d798d_idx'),
        ),
        migrations.AddIndex(
            model_name='historiallogin',
            index=models.Index(fields=['exitoso'], name='historial_l_exitoso_98cab1_idx'),
        ),
    ]
