-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.apellidos_usuario_natural
(
    id_apellido integer NOT NULL DEFAULT nextval('id_apellido_pk'::regclass),
    apellido character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT apellidos_usuario_natural_pkey PRIMARY KEY (id_apellido)
);

CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.authtoken_token
(
    key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT authtoken_token_pkey PRIMARY KEY (key),
    CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.categoria
(
    id_categoria integer NOT NULL DEFAULT nextval('id_categoria_pk'::regclass),
    nombre_categoria character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT categoria_pkey PRIMARY KEY (id_categoria)
);

CREATE TABLE IF NOT EXISTS public.credito_usuario_natural
(
    id_credito serial NOT NULL,
    id_cliente integer NOT NULL,
    limite_saldo numeric(10, 2),
    saldo_actual numeric(10, 2),
    saldo_disponible numeric(10, 2),
    id_estado integer NOT NULL,
    CONSTRAINT credito_usuario_natural_pkey PRIMARY KEY (id_credito)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.empleados
(
    id_empleado serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_empleado character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_rol integer NOT NULL,
    CONSTRAINT empleados_pkey PRIMARY KEY (id_empleado),
    CONSTRAINT empleados_correo_key UNIQUE (correo)
);

CREATE TABLE IF NOT EXISTS public.estadistica_ai
(
    id_estadistica integer NOT NULL DEFAULT nextval('id_estadistica_pk'::regclass),
    id_sucursal integer NOT NULL,
    productos_vendidos integer,
    ganancias double precision,
    gastos double precision,
    perdidas double precision,
    producto_mas_vendido character varying(255) COLLATE pg_catalog."default",
    comparacion_producto_mas_vendido character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT estadistica_ai_pkey PRIMARY KEY (id_estadistica)
);

CREATE TABLE IF NOT EXISTS public.estado
(
    id_estado serial NOT NULL,
    tipo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estado_pkey PRIMARY KEY (id_estado)
);

CREATE TABLE IF NOT EXISTS public.facturas_proveedor
(
    id_factura integer NOT NULL DEFAULT nextval('id_factura_pk'::regclass),
    id_proveedor integer NOT NULL,
    id_tienda integer NOT NULL,
    total_neto double precision,
    total_bruto double precision,
    descuento double precision,
    CONSTRAINT facturas_proveedor_pkey PRIMARY KEY (id_factura)
);

CREATE TABLE IF NOT EXISTS public.historial_login
(
    id_historial_login serial NOT NULL,
    id_empleado integer NOT NULL,
    fecha_inicio timestamp without time zone NOT NULL,
    fecha_fin timestamp without time zone,
    hora_fin time without time zone,
    tiempo_transcurrido interval,
    CONSTRAINT historial_login_pkey PRIMARY KEY (id_historial_login)
);

CREATE TABLE IF NOT EXISTS public.historial_movimientos
(
    id_historial_movimiento serial NOT NULL,
    id_empleado integer NOT NULL,
    accion text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT historial_movimientos_pkey PRIMARY KEY (id_historial_movimiento)
);

CREATE TABLE IF NOT EXISTS public.historial_ventas
(
    id_historial integer NOT NULL DEFAULT nextval('id_historial_pk'::regclass),
    id_producto integer NOT NULL,
    cantidad integer,
    fecha_venta date,
    precio_unitario double precision,
    precio_total double precision,
    id_cliente integer,
    id_proveedor integer,
    id_categoria integer,
    hora_registro time without time zone,
    CONSTRAINT historial_ventas_pkey PRIMARY KEY (id_historial)
);

CREATE TABLE IF NOT EXISTS public.inf_clientes
(
    id_cliente serial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default",
    cedula character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT inf_clientes_pkey PRIMARY KEY (id_cliente)
);

CREATE TABLE IF NOT EXISTS public.inf_login_usuario_natural
(
    id_usuario_natural_login integer,
    id_usuario serial NOT NULL,
    nombres character varying(100) COLLATE pg_catalog."default",
    apellidos character varying(100) COLLATE pg_catalog."default",
    correos character varying(255) COLLATE pg_catalog."default",
    cargo character varying(50) COLLATE pg_catalog."default",
    password_usuario_natural character varying(255) COLLATE pg_catalog."default",
    img_perfil text COLLATE pg_catalog."default",
    CONSTRAINT inf_login_usuario_natural_pkey PRIMARY KEY (id_usuario)
);

CREATE TABLE IF NOT EXISTS public.inf_producto
(
    product_id integer NOT NULL DEFAULT nextval('product_id_pk'::regclass),
    id_tienda integer NOT NULL,
    codigo_barras_local integer NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    precio_local numeric,
    nombre_producto character varying(40) COLLATE pg_catalog."default",
    id_categoria integer NOT NULL,
    imagen_producto bytea,
    marca character varying(30) COLLATE pg_catalog."default" NOT NULL,
    tiene_iva boolean,
    referencia character varying COLLATE pg_catalog."default",
    CONSTRAINT inf_producto_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.inf_proveedores
(
    id_proveedor integer NOT NULL DEFAULT nextval('id_proveedor_pk'::regclass),
    razon_social character varying(255) COLLATE pg_catalog."default",
    correo character varying(255) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    direccion character varying(255) COLLATE pg_catalog."default",
    n_registro_mercantil character varying(50) COLLATE pg_catalog."default",
    nit character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT inf_proveedores_pkey PRIMARY KEY (id_proveedor)
);

CREATE TABLE IF NOT EXISTS public.login_usuario
(
    id_login_usuario integer NOT NULL DEFAULT nextval('id_login_usuario_pk'::regclass),
    id_tienda integer,
    password character varying(250) COLLATE pg_catalog."default",
    correo_usuario character varying(255) COLLATE pg_catalog."default",
    last_login timestamp with time zone,
    is_active boolean,
    is_admin boolean,
    CONSTRAINT login_usuario_pkey PRIMARY KEY (id_login_usuario)
);

CREATE TABLE IF NOT EXISTS public.medios_pago
(
    id_pago integer NOT NULL DEFAULT nextval('id_pago_pk'::regclass),
    metodo_pago character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT medios_pago_pkey PRIMARY KEY (id_pago)
);

CREATE TABLE IF NOT EXISTS public.n_pedido
(
    id_n_pedido integer NOT NULL DEFAULT nextval('id_n_pedido_pk'::regclass),
    id_producto integer,
    cantidad_producto integer,
    precio_unitario_con_iva numeric(10, 0),
    precio_unitario_sin_iva numeric(10, 0),
    iva numeric(10, 0),
    subtotal numeric(10, 0),
    CONSTRAINT n_pedido_pkey PRIMARY KEY (id_n_pedido)
);

CREATE TABLE IF NOT EXISTS public.nombres_usuario_natural
(
    id_nombre integer NOT NULL DEFAULT nextval('id_nombre_pk'::regclass),
    nombre character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT nombres_usuario_natural_pkey PRIMARY KEY (id_nombre)
);

CREATE TABLE IF NOT EXISTS public.pedido
(
    id_pedido integer NOT NULL DEFAULT nextval('id_pedido_pk'::regclass),
    id_pagos integer,
    numero_fact_unico numeric(10, 0),
    fecha_emicion date,
    fecha_vencimiento date,
    CONSTRAINT pedido_pkey PRIMARY KEY (id_pedido)
);

CREATE TABLE IF NOT EXISTS public.productos
(
    id_producto integer NOT NULL DEFAULT nextval('id_producto_pk'::regclass),
    nombre_producto character varying(255) COLLATE pg_catalog."default",
    id_categoria integer NOT NULL,
    precio_unitario double precision,
    descripcion text COLLATE pg_catalog."default",
    imagen_producto character varying(255) COLLATE pg_catalog."default",
    marca character varying(100) COLLATE pg_catalog."default",
    tiene_iva boolean,
    CONSTRAINT productos_pkey PRIMARY KEY (id_producto)
);

CREATE TABLE IF NOT EXISTS public.registro_usuario_natural
(
    id_usuario_natural integer NOT NULL DEFAULT nextval('id_usuario_natural_pk'::regclass),
    id_nombre integer NOT NULL,
    id_apellido integer NOT NULL,
    id_telefono integer,
    correos_usuarios_natural character varying(255) COLLATE pg_catalog."default",
    direccion character varying(255) COLLATE pg_catalog."default",
    pasword_usuario_natural character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT registro_usuario_natural_pkey PRIMARY KEY (id_usuario_natural)
);

CREATE TABLE IF NOT EXISTS public.registro_ventas
(
    id_venta serial NOT NULL,
    id_cliente integer NOT NULL,
    fecha_venta date NOT NULL,
    precio_unitario numeric(10, 2) NOT NULL,
    precio_total numeric(10, 2) NOT NULL,
    CONSTRAINT registro_ventas_pkey PRIMARY KEY (id_venta)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id_rol serial NOT NULL,
    nombre_rol character varying(255) COLLATE pg_catalog."default" NOT NULL,
    permiso text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id_rol)
);

CREATE TABLE IF NOT EXISTS public.sucursales
(
    id_sucursal integer NOT NULL DEFAULT nextval('id_sucursal_pk'::regclass),
    nombre character varying(100) COLLATE pg_catalog."default",
    direccion character varying(255) COLLATE pg_catalog."default",
    ciudad character varying(100) COLLATE pg_catalog."default",
    socio character varying(100) COLLATE pg_catalog."default",
    estado character varying(50) COLLATE pg_catalog."default",
    subfijo character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT sucursales_pkey PRIMARY KEY (id_sucursal)
);

CREATE TABLE IF NOT EXISTS public.telefonos_usuario_natural
(
    id_telefono integer NOT NULL DEFAULT nextval('id_telefono_pk'::regclass),
    telefono character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT telefonos_usuario_natural_pkey PRIMARY KEY (id_telefono)
);

CREATE TABLE IF NOT EXISTS public.tiendas
(
    id_tienda integer NOT NULL DEFAULT nextval('id_tienda_pk'::regclass),
    nombre_tienda character varying(100) COLLATE pg_catalog."default",
    direccion character varying(255) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT tiendas_pkey PRIMARY KEY (id_tienda)
);

ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_login_usu FOREIGN KEY (user_id)
    REFERENCES public.login_usuario (id_login_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS authtoken_token_user_id_key
    ON public.authtoken_token(user_id);


ALTER TABLE IF EXISTS public.credito_usuario_natural
    ADD CONSTRAINT credito_usuario_natural_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.inf_clientes (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_fk FOREIGN KEY (user_id)
    REFERENCES public.login_usuario (id_login_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.empleados
    ADD CONSTRAINT empleados_id_rol_fkey FOREIGN KEY (id_rol)
    REFERENCES public.roles (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.empleados
    ADD CONSTRAINT fk_rol_empleado FOREIGN KEY (id_rol)
    REFERENCES public.roles (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estadistica_ai
    ADD CONSTRAINT fk_estadistica_sucursal FOREIGN KEY (id_sucursal)
    REFERENCES public.sucursales (id_sucursal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.facturas_proveedor
    ADD CONSTRAINT fk_factura_proveedor FOREIGN KEY (id_proveedor)
    REFERENCES public.inf_proveedores (id_proveedor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.facturas_proveedor
    ADD CONSTRAINT fk_factura_tienda FOREIGN KEY (id_tienda)
    REFERENCES public.tiendas (id_tienda) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historial_login
    ADD CONSTRAINT fk_empleado_login FOREIGN KEY (id_empleado)
    REFERENCES public.empleados (id_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historial_login
    ADD CONSTRAINT historial_login_id_empleado_fkey FOREIGN KEY (id_empleado)
    REFERENCES public.empleados (id_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.historial_movimientos
    ADD CONSTRAINT fk_usuario_natural_movimientos FOREIGN KEY (id_historial_movimiento)
    REFERENCES public.registro_usuario_natural (id_usuario_natural) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS historial_movimientos_pkey
    ON public.historial_movimientos(id_historial_movimiento);


ALTER TABLE IF EXISTS public.historial_movimientos
    ADD CONSTRAINT historial_movimientos_id_empleado_fkey FOREIGN KEY (id_empleado)
    REFERENCES public.empleados (id_empleado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.historial_ventas
    ADD CONSTRAINT fk_categoria_historial_ventas FOREIGN KEY (id_categoria)
    REFERENCES public.categoria (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historial_ventas
    ADD CONSTRAINT fk_cliente_historial_ventas FOREIGN KEY (id_cliente)
    REFERENCES public.inf_clientes (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historial_ventas
    ADD CONSTRAINT fk_historial_categoria FOREIGN KEY (id_categoria)
    REFERENCES public.categoria (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historial_ventas
    ADD CONSTRAINT fk_historial_producto FOREIGN KEY (id_producto)
    REFERENCES public.productos (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historial_ventas
    ADD CONSTRAINT fk_historial_proveedor FOREIGN KEY (id_proveedor)
    REFERENCES public.inf_proveedores (id_proveedor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historial_ventas
    ADD CONSTRAINT fk_proveedor_historial_ventas FOREIGN KEY (id_proveedor)
    REFERENCES public.inf_proveedores (id_proveedor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inf_clientes
    ADD CONSTRAINT fk_tienda_cliente FOREIGN KEY (id_cliente)
    REFERENCES public.tiendas (id_tienda) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS inf_clientes_pkey
    ON public.inf_clientes(id_cliente);


ALTER TABLE IF EXISTS public.inf_login_usuario_natural
    ADD CONSTRAINT fk_usuario_natural_login FOREIGN KEY (id_usuario_natural_login)
    REFERENCES public.registro_usuario_natural (id_usuario_natural) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inf_login_usuario_natural
    ADD CONSTRAINT inf_login_usuario_natural_id_usuario_natural_fkey FOREIGN KEY (id_usuario_natural_login)
    REFERENCES public.registro_usuario_natural (id_usuario_natural) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inf_producto
    ADD CONSTRAINT fk_categoria_producto FOREIGN KEY (id_categoria)
    REFERENCES public.categoria (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.productos
    ADD CONSTRAINT fk_categoria_producto FOREIGN KEY (id_categoria)
    REFERENCES public.categoria (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registro_usuario_natural
    ADD CONSTRAINT fk_apellido_usuario FOREIGN KEY (id_apellido)
    REFERENCES public.apellidos_usuario_natural (id_apellido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registro_usuario_natural
    ADD CONSTRAINT fk_apellido_usuario_natural FOREIGN KEY (id_apellido)
    REFERENCES public.apellidos_usuario_natural (id_apellido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registro_usuario_natural
    ADD CONSTRAINT fk_nombre_usuario FOREIGN KEY (id_nombre)
    REFERENCES public.nombres_usuario_natural (id_nombre) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registro_usuario_natural
    ADD CONSTRAINT fk_nombre_usuario_natural FOREIGN KEY (id_nombre)
    REFERENCES public.nombres_usuario_natural (id_nombre) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registro_usuario_natural
    ADD CONSTRAINT fk_telefono_usuario FOREIGN KEY (id_telefono)
    REFERENCES public.telefonos_usuario_natural (id_telefono) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registro_usuario_natural
    ADD CONSTRAINT fk_telefono_usuario_natural FOREIGN KEY (id_telefono)
    REFERENCES public.telefonos_usuario_natural (id_telefono) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registro_ventas
    ADD CONSTRAINT registro_ventas_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.inf_clientes (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;