"""
Django settings for nova project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import datetime
from datetime import timedelta
from django.utils import timezone
from corsheaders.defaults import default_headers

# Cargar variables de entorno desde .env
env_file = BASE_DIR / '.env'
if env_file.exists():
    from dotenv import load_dotenv
    load_dotenv(env_file)





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


dt_naive = datetime.datetime.now()
dt_aware = timezone.make_aware(dt_naive, timezone=datetime.timezone.utc)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-9)6^ej5!o6d^y)n7+#p+i6)_%3_$=o*^liuplt)^mqhwbmz9*f')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [
    'dagi.co',
    '31.97.14.61',
    'localhost',
    '127.0.0.1',
    '.dagi.co',
    'backend',
    'nginx',
    'frontend'
]



STATIC_ROOT = BASE_DIR / 'staticfiles'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],

    # Renderizado (para API en navegador y JSON en frontend)
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),

    # Manejador de errores
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',

    # Autenticación: COMENTAR SessionAuthentication para APIs puras
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',  # ← Comentar esta línea
        'rest_framework.authentication.BasicAuthentication',
    ),

    # Permisos por defecto
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}





# Application definition
INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # Para blacklist de tokens
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',
    'rest_auth',
    'cities_light',
    'nova',
    'login',
    'django_extensions',
    'main_dashboard',
    'django_filters',


]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'main_dashboard.middleware.DisableCSRFForAPIMiddleware',  
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nova.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nova.wsgi.application'
AUTH_USER_MODEL = 'nova.LoginUsuario'




# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'bd_madre'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'zuleta18'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    },
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'America/Bogota'
USE_TZ = True


USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Credenciales de Mailjet - USAR VARIABLES DE ENTORNO EN PRODUCCIÓN
MAILJET_API_KEY = os.environ.get('MAILJET_API_KEY', '78eeb3d1a064eee752054c93d5317fbf')
MAILJET_API_SECRET = os.environ.get('MAILJET_API_SECRET', 'ef3c1d75feaebea65382a59a7e4546f7')
MAILJET_EMAIL_FROM = os.environ.get('MAILJET_EMAIL_FROM', 'nova@dagi.co')



FORCE_SCRIPT_NAME = '/api'
USE_X_FORWARDED_HOST = True


CORS_ALLOWED_ORIGINS = [
    "https://dagi.co",      # el dominio raíz sin subdominio
    "http://31.97.14.61",  # IP u otros orígenes si usas
]

# settings.py
CORS_ALLOW_CREDENTIALS = True 
CORS_ALLOW_ALL_ORIGINS = False

CSRF_TRUSTED_ORIGINS = [
    "http://31.97.14.61",
    "https://dagi.co",
    "https://*.dagi.co",# en caso de que se inplemente un front diferente para cada tienda
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https:\/\/([a-z0-9-]+\.)*dagi\.co$",  # cualquier subdominio (incluye sub-subdominios)
]




#para la expiracion del token jwt
# Aumentado para mejorar experiencia de usuario y reducir necesidad de refresh
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),  # Cambiado de 30 min a 8 horas
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),  # Cambiado de 7 a 30 días
    'ROTATE_REFRESH_TOKENS': True,  # Rotar refresh tokens
    'BLACKLIST_AFTER_ROTATION': True,  # Poner en blacklist el antiguo
    'UPDATE_LAST_LOGIN': True,  # Actualizar ultimo_login automáticamente

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'type',

    # Tokens incluidos en respuesta
    'TOKEN_OBTAIN_SERIALIZER': 'main_dashboard.serializers.TokenObtainPairSerializer',
    'TOKEN_REFRESH_SERIALIZER': 'main_dashboard.serializers.TokenRefreshSerializer',
    'TOKEN_VERIFY_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenVerifySerializer',
    'TOKEN_BLACKLIST_SERIALIZER': 'rest_framework_simplejwt.serializers.BlacklistTokenSerializer',
}



#dominio
BASE_DOMAIN = os.environ.get('BASE_DOMAIN', 'dagi.co')  # dominio principal


CORS_ALLOW_HEADERS = list(default_headers) + [
    'authorization',
    'x-csrftoken',
    'content-type',
]



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}






# Configuración para archivos multimedia
MEDIA_URL = '/media/'
# MEDIA_ROOT debe apuntar a /app/media (no /app/nova/media)
# BASE_DIR es /app/nova, así que usamos pathlib para ir al directorio padre
MEDIA_ROOT = '/app/media'

