# Generated by Django 5.0.6 on 2025-06-22 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUsuario',
            fields=[
                ('id_login_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_tienda', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=250)),
                ('correo_usuario', models.EmailField(max_length=255, unique=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'login_usuario',
            },
        ),
        migrations.CreateModel(
            name='ApellidosUsuarioNatural',
            fields=[
                ('id_apellido', models.AutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'apellidos_usuario_natural',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_numero', models.CharField(max_length=100)),
                ('ciudad_estado', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='HistorialVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InfProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('n_registro_mercantil', models.CharField(blank=True, max_length=50, null=True)),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'inf_proveedores',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=30, null=True)),
                ('db_nombre', models.CharField(blank=True, max_length=150, unique=True)),
                ('db_password', models.CharField(blank=True, max_length=100)),
                ('db_usuario', models.CharField(blank=True, max_length=100)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=30)),
                ('nombre_propietario', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('direccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tienda', to='nova.direccion')),
                ('documento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nova.documento')),
            ],
        ),
        migrations.CreateModel(
            name='Dominios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(blank=True, max_length=255, unique=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios', to='nova.tiendas')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='nova.tiendas'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nova.tipodocumento'),
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nova.authuser')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': True,
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nova.authuser')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': True,
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('tienda', 'tipo')},
        ),
    ]
