# Generated by Django 5.0.6 on 2025-06-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiendas',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='tiendas',
            table='tiendas',
        ),
    ]
