# Generated by Django 5.0.6 on 2025-06-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0002_alter_tiendas_options_alter_tiendas_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiendas',
            options={},
        ),
        migrations.AlterModelTable(
            name='tiendas',
            table=None,
        ),
    ]
