# Generated by Django 5.0.6 on 2025-06-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0003_alter_tiendas_options_alter_tiendas_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='tiendas',
            name='db_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tiendas',
            name='nit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
