# Generated by Django 5.0.6 on 2025-06-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0004_alter_usuarios_options_alter_tiendas_db_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendas',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
