# Generated by Django 5.0.6 on 2025-06-30 03:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0005_tiendas_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendas',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiendas',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
