# Generated by Django 5.0.6 on 2025-07-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0006_tiendas_email_tiendas_es_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendas',
            name='es_activo',
            field=models.BooleanField(default=False),
        ),
    ]
