# Generated by Django 5.0.6 on 2025-07-02 02:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0007_alter_tiendas_es_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendas',
            name='usuario',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
