# Generated by Django 5.0.6 on 2025-07-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0008_tiendas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
