# Generated by Django 5.0.6 on 2025-07-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0009_alter_tiendas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
