# Generated by Django 5.0.6 on 2025-07-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('nova', '0010_alter_tiendas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginusuario',
            name='id_login_usuario',
            field=models.AutoField(db_column='id_login_usuario', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='loginusuario',
            old_name='id_login_usuario',
            new_name='id',
        ),
        migrations.AddField(
            model_name='loginusuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='loginusuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='loginusuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
