# Generated by Django 5.0.6 on 2025-07-04 01:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0011_alter_loginusuario_id_login_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginusuario',
            name='id_tienda',
        ),
        migrations.AddField(
            model_name='loginusuario',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operario', 'Operario')], default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='loginusuario',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='nova.tiendas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loginusuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
