# Generated by Django 5.0.6 on 2025-07-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0012_remove_loginusuario_id_tienda_loginusuario_creado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginusuario',
            name='usuario',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
