# Generated by Django 5.0.6 on 2025-07-04 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0013_loginusuario_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.RenameField(
            model_name='tiendas',
            old_name='email',
            new_name='correo_usuario',
        ),
        migrations.AlterField(
            model_name='loginusuario',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_legacy', to='nova.tiendas'),
        ),
    ]
