# Generated by Django 5.0.6 on 2025-07-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0014_delete_usuarios_rename_email_tiendas_correo_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginusuario',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
