# Generated by Django 5.0.6 on 2025-07-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0015_loginusuario_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('almacen', 'Encargado de Almacén'), ('vendedor', 'Vendedor'), ('operario', 'Operario')], default='admin', max_length=20),
        ),
    ]
