# Generated by Django 5.0.6 on 2025-07-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0016_alter_loginusuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginusuario',
            name='sucursal_id',
            field=models.IntegerField(blank=True, db_column='id_sucursal_default', null=True),
        ),
    ]
