# Generated by Django 5.1.5 on 2026-02-11 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_dashboard', '0007_alter_factura_anulada_por'),
        ('nova', '0017_loginusuario_sucursal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginusuario',
            name='sucursal_id',
        ),
        migrations.AddField(
            model_name='loginusuario',
            name='id_sucursal_default',
            field=models.ForeignKey(db_column='id_sucursal_default', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='main_dashboard.sucursales'),
        ),
        migrations.CreateModel(
            name='LoginUsuarioBodega',
            fields=[
                ('id_login_usuario_bodega', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('id_bodega', models.ForeignKey(db_column='id_bodega', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignaciones', to='main_dashboard.bodega')),
                ('id_login_usuario', models.ForeignKey(db_column='id_login_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='bodegas_asignaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_usuario_bodega',
            },
        ),
        migrations.AddField(
            model_name='loginusuario',
            name='bodegas_asignadas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_asignados', through='nova.LoginUsuarioBodega', to='main_dashboard.bodega'),
        ),
        migrations.AddIndex(
            model_name='loginusuariobodega',
            index=models.Index(fields=['id_login_usuario'], name='login_usuar_id_logi_80c0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='loginusuariobodega',
            index=models.Index(fields=['id_bodega'], name='login_usuar_id_bode_213280_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loginusuariobodega',
            unique_together={('id_login_usuario', 'id_bodega')},
        ),
    ]
