# Generated by Django 5.1.5 on 2026-02-18 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0018_add_bodegas_asignadas_to_login_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteEcommerce',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_persona', models.CharField(choices=[('NAT', 'Natural'), ('JUR', 'Jurídica')], default='NAT', max_length=3)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('token_activacion', models.CharField(blank=True, max_length=255, null=True)),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_ecommerce', to='nova.tiendas')),
            ],
            options={
                'verbose_name': 'Cliente E-commerce',
                'verbose_name_plural': 'Clientes E-commerce',
                'db_table': 'clientes_ecommerce',
                'indexes': [models.Index(fields=['email'], name='clientes_ec_email_dac14e_idx'), models.Index(fields=['tienda'], name='clientes_ec_tienda__60f94f_idx'), models.Index(fields=['is_active'], name='clientes_ec_is_acti_c169ed_idx')],
            },
        ),
    ]
